### PR TITLE
fix(theme-default): features link in the homepage does not contain the base path

### LINKED ISSUE #1234: [Bug]: Features link in the homepage does not contain the base path
### 版本信息

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
    Memory: 5.40 GB / 15.73 GB
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527


    "@modern-js/core": "2.54.5",
    "@modern-js/eslint-config": "2.54.5",
    "@modern-js/module-tools": "2.54.5",
    "@modern-js/plugin-rspress": "1.25.2",
```

### 问题详情

生成的主页中features模块对应的跳转链接没有带上配置的base

### 复现链接

https://github.com/asurance/openify

### 复现步骤

项目对应文档地址：https://asurance.github.io/openify/
image
上方的hero区点击跳转正常，下方features点击跳转后会缺少base导致访问404(本地调试正常，部署后异常)
对应配置
```
hero:
  name: Openify
  actions:
    - theme: brand
      text: 欢迎使用
      link: /guide/intro/welcome
    - theme: alt
      text: 快速上手
      link: /guide/intro/getting-started

features:
  - title: 静态调用
    link: /guide/feature/static-call
  - title: Promise化
    link: /guide/feature/promisify
  - title: 组件库无关
```

### PR DESCRIPTION
**Pull request by shulaoda**
## Related Issue
Fixed #1234 

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

**Comment by shulaoda** [comment]
This feature might impact users. Please notify users after the release. It might be appropriate to release it as a minor version.

File: packages/theme-default/src/components/HomeFeature/index.tsx [hunk 1]
```diff
@@ -9,13 +12,20 @@ const getGridClass = (feature: Feature): string => {
...
+  routePath: string;
+}) {
   const features = frontmatter?.features;
 
   return (
     <div className="overflow-hidden m-auto flex flex-wrap max-w-6xl">
       {features?.map(feature => {
-        const { icon, title, details, link } = feature;
+        const { icon, title, details, link: rawLink } = feature;
+        const link = normalizeHrefInRuntime(withBase(rawLink, routePath));
```
Comment (Timeless0911) [inline packages/theme-default/src/components/HomeFeature/index.tsx:28]: We should use `isExternalUrl` from `@rspress/shared` to determine a url is external or not, then
```ts
const link = isExternalUrl(link) ? link : normalizeHrefInRuntime(withBase(link, routePath))
```

File: packages/theme-default/src/components/HomeHero/index.tsx [hunk 2]
```diff
@@ -72,7 +72,9 @@ export function HomeHero({
                   <Button
                     type="a"
                     text={renderHtmlOrText(action.text)}
-                    href={normalizeHref(withBase(action.link, routePath))}
+                    href={normalizeHrefInRuntime(
```
Comment (Timeless0911) [inline packages/theme-default/src/components/HomeHero/index.tsx:75]: do same external url judgement here

**Review by Timeless0911 — APPROVED** [review]
