### PR TITLE
fix(theme-default): search logic stop when header matches

### LINKED ISSUE #1372: [Bug]: search will stop when keyword in title(h1, h2, h3...), even the keyword also exists in content
### 版本信息

```sh
System:
    OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 10.97 GB / 15.62 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  npmPackages:
    rspress: ^1.28.0 => 1.28.2
```

### 问题详情

md 文档内容类似于:

```md
# 标题

## 批量操作手续费

点击【批量操作手续费】，可以进行【新增】、【修改】、【删除】三项操作，点【新增】操作可以批量增加产品。

手续费设置界面，选择需设置的产品，配置对应比例，点击【保存】。【固定费率】如无特殊要求，建议优先选【否】，配置区间手续费。点击【确认新增】，完成批量新增操作。

保存是标题中没有的文案，多次出现的保存可以搜索到。

保存在这里。

## 二级标题

或者保存在这里。
```

当搜索 `手续费` 时，只能搜索到 `标题 > 批量操作手续费`：
image
而搜索 “保存” 时，可以搜索到多个结果：
image

### 复现链接

https://codesandbox.io/p/devbox/naughty-darwin-pqq75j?workspaceId=edafb2d3-8406-4734-ac75-3017fd4fe3d8

### 复现步骤

1. pnpm dev
2. 浏览器打开 http://localhost:3000
3. 点击搜索框，键入“手续费”

想要的结果是能够搜索标题中的 `批量操作手续费` 以及内容中的 `手续费`。

### PR DESCRIPTION
**Pull request by liuwenzhuang**
This commit fixes #1372

## Related Issue

[](https://github.com/web-infra-dev/rspress/issues/1372)

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

File: packages/theme-default/src/components/Search/logic/search.ts [hunk 1]
```diff
@@ -260,18 +265,22 @@ export class PageSearcher {
...
-        header: currentHeader?.text ?? item.title,
-        statement,
-        highlightInfoList,
-        link: `${domain}${normalizeHref(item.routePath)}${
-          currentHeader ? `#${currentHeader.id}` : ''
-        }`,
-        query,
-        group: this.#options.extractGroupName(item.routePath),
-      });
+      if (!currentHeader || !matchHeaderSet?.has(currentHeader)) {
```
Comment (Timeless0911) [inline packages/theme-default/src/components/Search/logic/search.ts:268]: This if sentence seems no need since already return `if (currentHeader && matchHeaderSet?.has(currentHeader))`?

Comment (liuwenzhuang) [reply packages/theme-default/src/components/Search/logic/search.ts:268]: return of `if  (currentHeader && matchHeaderSet?.has(currentHeader))` located at `queryIndex === -1` condition, this if sentence run in `queryIndex !== -1` condition.

Comment (Timeless0911) [reply packages/theme-default/src/components/Search/logic/search.ts:268]: Get it, we can use `const hasHeader = currentHeader && matchHeaderSet?.has(currentHeader`, and use `hasHeader` and `!hasHeader`.

Comment (liuwenzhuang) [reply packages/theme-default/src/components/Search/logic/search.ts]: Good idea, I add a function to check is header matched.

**Review by Timeless0911 — APPROVED** [review]
👍LGTM
